---
- name: configure ipv4 addresses
  ios_l3_interfaces:
    config:
      - name: "{{ item.0.id }}"
        ipv4:
        - address: "{{ item.1 }}"
  loop: "{{ interfaces.ipv4_addresses }}"
  loop: interfaces.ipv4_addresses is defined
