---
- name: enable rip version 2
  ios_config:
    parents: router rip
    lines:
      - version 2
  when: rip.version is defined
  tags:
    - rip
- name: enable ripv2 passive-interface
  ios_config:
    parents: router rip
    lines:
      - passive-interface {{ item }}
  with_items:
      - "{{ ipv4routing.passive }}"
  when: ipv4routing.passive is defined
  tags:
    - rip
- name: enable eigrp4 interfaces
  ios_config:
    parents: router eigrp {{ ipv4routing.as }}
    lines:
      - network {{ item.ipv4 }}
  with_items:
      - "{{ rip }}"
  tags:
    - rip
