---
- name: enable rip version 2
  ios_config:
    defaults: yes
    parents: router rip
    lines:
      - version 2
  when:
    - routing.rip is defined
- name: enable rip passive-interface
  ios_config:
    defaults: yes
    parents: router rip
    lines:
      - passive-interface {{ item }}
  loop: "{{ routing.passive }}"
  when:
    - routing.rip is defined
    - item is defined
- name: enable rip interfaces
  ios_config:
    defaults: yes
    parents: router rip
    lines:
      - network {{ item }}
  loop: "{{ routing.rip }}"
  when:
    - routing.rip is defined
    - item is defined
