---
- name: redistribute static nat route to rip
  ios_config:
    defaults: yes
    parents: router rip
    lines:
      - default-information originate
  when:
    - interfaces | selectattr('rip', 'defined') | list
    - nat is defined
