---
- hosts: core
  gather_facts: False
  roles:
    - role: common
    - role: interface
    - role: ipv4
    - role: ipv6
    - role: ipv4-routing
    - role: ipv6-routing
    - role: fhrp
    - role: rip
      when: '"rip" in routing_ipv4'
    - role: eigrp4
      when: '"eigrp4" in routing_ipv4'
    - role: ospfv2
      when: '"ospfv2" in routing_ipv4'
    - role: eigrp6
      when:
        - '"eigrp6" in routing_ipv6'
    - role: ospfv3
      when:
        - '"ospfv3" in routing_ipv6'
    - role: dhcp-server
- hosts: R1
  gather_facts: False
  roles:
    - role: nat
- hosts: core
  gather_facts: False
  roles:
    - role: write
