---
- hosts: core
  gather_facts: False
  roles:
    - common
    - interface
    - ipv4
    - rip # rip, eigrp4, ospfv2
    - ipv6-routing
    - ipv6
    - eigrp6
    - dhcp-server
- hosts: R1
  gather_facts: False
  roles:
    - nat
- hosts: core
  gather_facts: False
  roles:
    - write
