---
- hosts: core
  gather_facts: False
  roles:
    - role: common
    - role: interface
    - role: ipv4
    - role: rip
      when: routing.ipv4 == 'rip'
    - role: eigrp4
      when: routing.ipv4 == 'eigrp4'
    - role: eigrp6
      when: routing.ipv6 == 'eigrp6'
    - role: dhcp-server
- hosts: R1
  gather_facts: False
  roles:
    - role: nat
- hosts: core
  gather_facts: False
  roles:
    - role: write
