---
- name: configure trunk ports
  ios_config:
    parents: interface {{ item.0.id }}
    lines:
      - switchport trunk encapsulation dot1q
      - switchport trunk native vlan {{ item.1.native }}
      - switchport mode trunk
  loop: "{{ interfaces|subelements('trunk', skip_missing=True) }}"
