---
- name: Merge provided configuration with device configuration
  ios_l2_interfaces:
    config:
      - name: "{{ item.0.id }}"
        trunk:
          native_vlan: "{{ item.1.native }}"
          encapsulation: dot1q
#          allowed_vlan: 10-20, 40
#          pruning_vlan: 10,20
  loop: "{{ interfaces|subelements('trunk', skip_missing=True) }}"
