---
- name: configure trunk ports
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - switchport trunk encapsulation dot1q
      - switchport trunk native vlan {{ item.native }}
      - switchport mode trunk
  loop: "{{ trunks }}"
  when: trunks is defined
