---
- name: configure access ports
  ios_config:
    defaults: yes
    parents: interface {{ item.0.id }}
    lines:
      - switchport mode access
      - switchport access vlan {{ item.1.vlan }}
  loop: "{{ interfaces|subelements('access', skip_missing=True) }}"
  when: interfaces is defined
- name: stp protection on access ports
  ios_config:
    defaults: yes
    parents: interface {{ item.0.id }}
    lines:
      - spanning-tree portfast edge
      - spanning-tree bpduguard enable
  loop: "{{ interfaces|subelements('access', skip_missing=True) }}"
  when: interfaces is defined
