---
- name: configure access ports
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - switchport mode access
      - switchport access vlan {{ item.vlan }}
  loop: "{{ access }}"
  when: access is defined
- name: stp protection on access ports
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - spanning-tree portfast
      - spanning-tree bpduguard enable
  loop: "{{ access }}"
  when: access is defined
