- import_tasks: create_vlans.yml
  when: ansible_network_os == 'ios'
  tags:
    - vlans
    - l2
- import_tasks: configure_access_ports.yml
  when: ansible_network_os == 'ios'
  tags:
    - vlans
    - l2
- import_tasks: configure_trunk_ports.yml
  when: ansible_network_os == 'ios'
  tags:
    - vlans
    - l2
