---
- name: disable stub switchports
  ios_interfaces:
    config:
      - name: "{{ item.0.id }}"
        enabled: False
  loop: "{{ interfaces|subelements('stub', skip_missing=True)|list }}"
  when:
    - stubvlan is defined
- name: create stub vlan
  ios_vlans:
    config:
      - name: "{{ stubvlan.name }}"
        vlan_id: "{{ stubvlan.id }}"
        state: active
        shutdown: disabled
  when:
    - stubvlan is defined
- name: configure stub access ports
  ios_config:
    parents: interface {{ item.0.id }}
    lines:
      - switchport mode access
      - switchport access vlan {{ stubvlan.id }}
  loop: "{{ interfaces|subelements('stub', skip_missing=True) }}"
  when:
    - stubvlan is defined
- name: stp protection on stub access ports
  ios_config:
    parents: interface {{ item.0.id }}
    lines:
      - spanning-tree portfast edge
      - spanning-tree bpduguard enable
  loop: "{{ interfaces|subelements('stub', skip_missing=True)|list }}"
  when:
    - stubvlan is defined
