---
galaxy_info:
  author: goffinet
  description: enable IPv6 routing
  license: CC-BY-4.0
  min_ansible_version: 2.9
  galaxy_tags:
    - cisco
    - iosv
    - ccna
    - ipv6
    - routing
dependencies:
  - role: interface
  - role: ipv6
