- name: create vlans
  ios_vlans:
    config:
      - name: "{{ item.name }}"
        vlan_name: "{{ item.name }}"
        state: active
        shutdown: disabled
  loop: "{{ vlans }}"
  when:
    - item.name is defined
    - item.name is defined
