---
- name: disable stub switchports
  ios_interfaces:
    config:
      - name: "{{ item.name }}"
        enabled: False
  loop: "{{ interfaces }}"
  when: item.stub is defined
- name: create stub vlan
  ios_vlans:
    config:
      - name: "{{ stubvlan.name }}"
        vlan_name: "{{ stubvlan.name }}"
        state: active
        shutdown: disabled
  when:
    - stubvlan is defined
- name: configure stub access ports
  ios_config:
    defaults: yes
    parents: interface {{ item.name }}
    lines:
      - switchport mode access
      - switchport access vlan {{ stubvlan.name }}
  loop: "{{ interfaces }}"
  when:
    - stubvlan is defined
    - item.stub is defined
- name: stp protection on stub access ports
  ios_config:
    defaults: yes
    parents: interface {{ item.name }}
    lines:
      - spanning-tree portfast edge
      - spanning-tree bpduguard enable
  loop: "{{ interface }}"
  when:
    - stubvlan is defined
    - item.stub is defined
