---
- name: define the version of stp
  ios_config:
    lines: spanning-tree mode {{ stp.mode }}
  when: stp.mode is defined
- name: define the stp root primary
  ios_config:
    lines: "spanning-tree vlan {{ item }} priority 4096"
    diff_ignore_lines:
      - spanning-tree vlan .*
  loop: "{{ stp.primary }}"
  when: stp.primary is defined
- name: define the stp root secondary
  ios_config:
    lines: "spanning-tree vlan {{ item }} priority 8184"
    diff_ignore_lines:
      - spanning-tree vlan .*
  loop: "{{ stp.secondary }}"
  when: stp.secondary is defined
