---
- name: define the version of stp
  ios_config:
    defaults: yes
    lines: spanning-tree mode {{ stp.mode }}
  when: stp.mode is defined
- name: define the stp root primary
  ios_config:
    defaults: yes
    lines: "spanning-tree vlan {{ stp.primary }} root primary"
  when: stp.primary is defined
- name: define the stp root secondary
  ios_config:
    defaults: yes
    lines: "spanning-tree vlan {{ stp.secondary }} root secondary"
  when: stp.secondary is defined
