---
galaxy_info:
  author: goffinet
  description: cisco iosv role
  license: CC-BY-4.0
  min_ansible_version: 2.9
  galaxy_tags:
    - cisco
    - iosv
    - ccna
dependencies:
  - role: interface
  - role: ipv4
  - role: ipv4-routing
