---
- name: enable ipv6
  ios_config:
    parents: "interface {{ item.0.id }}"
    lines:
      - ipv6 enable
      - "ipv6 address {{ item.1 }} link-local"
  loop: "{{ interface|subelements('ipv6_link_local_addresses') }}"

# https://docs.ansible.com/ansible/devel/modules/ios_l3_interface_module.html#ios-l3-interface-module
- name: configure ipv6 addresses
  ios_l3_interfaces:
    config:
      - name: "{{ item.0.id }}"
        ipv6:
        - address: "{{ item.1 }}"
  loop: "{{ interface|subelements('ipv6_ula_uga_addresses, skip_missing=True') }}"
  when: interface.ipv6_ula_uga_addresses is defined
