---
- name: disable switchport on switch interface
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - no switchport
  loop: "{{ interface }}"
  when: item.noswitchport is defined
  tags:
    - interface
- name: enable access switchports
  ios_interfaces:
    config:
      - name: "{{ item.id }}"
        enabled: True
        description: TODO
  loop: "{{ access }}"
  when: access is defined
  tags:
    - interface
- name: enable trunk switchports
  ios_interfaces:
    config:
      - name: "{{ item.id }}"
        enabled: True
        description: TODO
  loop: "{{ trunks }}"
  when: trunks is defined
  tags:
    - interface
- name: enable ip interface
  ios_interfaces:
    config:
      - name: "{{ item.id }}"
        enabled: True
        description: TODO
  loop: "{{ interface }}"
  when: interface is defined
  tags:
    - interface
