---
- name: disable switchport on switch interface
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - no switchport
  loop: "{{ interfaces }}"
  when: item.noswitchport is defined
  tags:
    - interface
- name: enable interface
  ios_interfaces:
    config:
      - name: "{{ item.id }}"
        enabled: True
        description: "{{ item.description }}"
  loop: "{{ interfaces }}"
  when: interfaces is defined
  tags:
    - interface
