---
- name: disable switchport on switch interface
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - no switchport
  with_items: "{{ interface }}"
  when: item.noswitchport is defined
  tags:
    - interface
- name: enable access switchports
  ios_interface:
    name: "{{ item.id }}"
    enabled: true
    state: present
    description: TODO
  with_items: "{{ access }}"
  tags:
    - interface
- name: enable trunk switchports
  ios_interface:
    name: "{{ item.id }}"
    enabled: true
    state: present
    description: TODO
  with_items: "{{ trunk }}"
  tags:
    - interface
- name: enable ip interface
  ios_interface:
    name: "{{ item.id }}"
    enabled: true
    state: present
    description: TODO
  with_items: "{{ interface }}"
  tags:
    - interface
