---
- name: configure ipv6 addresses
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - ipv6 enable
      - ipv6 address {{ item.net6 }}
  loop: "{{ lan6 }}"
  when: lan6 is defined
