---
- name: enable ipv6 and configure link-local address
  ios_config:
    defaults: yes
    parents: "interface {{ item.0.id }}"
    lines:
      - "ipv6 enable"
      - "ipv6 address {{ item.1 | ipaddr('address') }} link-local"
  loop: "{{ interfaces | subelements('ipv6_link_local_addresses', skip_missing=True) }}"
  when:
        - item.1 is regex("^FE80:")
#       - item.1 | ipv6
- name: configure ula/uga ipv6 addresses
#  ios_l3_interfaces:
#    config:
#      - name: "{{ item.0.id }}"
#        ipv6:
#        - address: "{{ item.1 }}"
  ios_config:
    defaults: yes
    parents: "interface {{ item.0.id }}"
    lines:
      - "ipv6 address {{ item.1 'host/prefix' }}"
  loop: "{{ interfaces | subelements('ipv6_ula_uga_addresses', skip_missing=True) }}"
  when:
        - item.1 is regex("^FD[0-9A-F]?[0-9A-F]?:") or item.1 | ipaddr('public')
#        - item.1 | ipv6
