---
- name: enable ipv6 and configure link-local address
  ios_config:
    defaults: yes
    parents: "interface {{ item.0.id }}"
    lines:
      - ipv6 enable
      - "ipv6 address {{ item.1 }} link-local"
  loop: "{{ interfaces|subelements('ipv6_link_local_addresses', skip_missing=True) }}"
- name: configure ipv6 addresses
  ios_l3_interfaces:
    config:
      - name: "{{ item.0.id }}"
        ipv6:
        - address: "{{ item.1 }}"
  loop: "{{ interfaces|subelements('ipv6_ula_uga_addresses', skip_missing=True) }}"
