---
galaxy_info:
  author: goffinet
  description: configure dhcp server and dhcp pools
  license: CC-BY-4.0
  min_ansible_version: 2.9
  galaxy_tags:
    - cisco
    - iosv
    - ccna
    - dhcp-server
dependencies:
  - role: interface
  - role: ipv4
