---
- name: create stub vlan
  ios_vlan:
    vlan_id: "{{ stubvlan.id }}"
    state: present
    name: "{{ stubvlan.name }}"
  when:
    - switchports is defined
    - stubvlan is defined
- name: secure access switchports ports
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - switchport mode access
      - switchport access vlan {{ stubvlan.id }}
      - switchport port-security
      - switchport port-security mac-address sticky
      - spanning-tree portfast
      - spanning-tree bpduguard enable
      - shutdown
  with_items: "{{ switchports }}"
  when:
    - switchports is defined
    - stubvlan is defined
