---
- name: create stub vlan
  ios_vlans:
    config:
      - name: "{{ stubvlan.name }}"
        vlan_id: "{{ stubvlan.id }}"
        state: active
        shutdown: disabled
  when:
    - switchports is defined
    - stubvlan is defined
- name: switchports in access on stub vlan
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - switchport mode access
      - switchport access vlan {{ stubvlan.id }}
  loop: "{{ switchports }}"
  when:
    - switchports is defined
    - stubvlan is defined
- name: portfast and bpduguard
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - spanning-tree portfast
      - spanning-tree bpduguard enable
  loop: "{{ switchports }}"
  when:
    - switchports is defined
    - stubvlan is defined
- name: shutdown all switchports
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - shutdown
  loop: "{{ switchports }}"
  when:
    - switchports is defined
    - stubvlan is defined
