---
- import_tasks: enable_ospfv2.yml
  when: ansible_network_os == 'ios'
  tags:
    - ospfv2
- import_tasks: static_to_ospfv2.yml
  when:
    - ansible_network_os == 'ios'
    - nat is defined
  tags:
    - ospfv2
