---
- name: CONFIGURE IPv4 ADDRESSES
  hosts: core
  gather_facts: false
  tasks:
    - name: configure ipv4 adresses
      ios_config:
        parents: interface {{ item.id }}
        lines:
          - ip address {{ item.ipv4 }} {{ item.netmask }} 
      with_items: "{{ interface }}"
      register: print_output
    - debug: var=print_output

