---
- name: CONFIGURE IPv6 ADDRESSES
  hosts: core
  gather_facts: false
  tasks:
    - name: configure ipv6 addresses
      ios_config:
        parents: interface {{ item.id }}
        lines:
          - ipv6 enable
          - ipv6 address {{ item.net6 }}
      with_items: "{{ lan6 }}"
      register: print_output
    - debug: var=print_output

