---
- name: DISABLE EIGRP IPv4
  hosts: core
  gather_facts: false
  tasks:
    - name: disable eigrp ipv4
      ios_config:
        lines: no router eigrp {{ item.as }}
      with_items: "{{ ipv4routing }}"
      register: print_output
    - debug: var=print_output
