---
- name: DISABLE EIGRP IPv6
  hosts: core
  gather_facts: false
  tasks:
    - name: disable eigrp ipv6
      ios_config:
        lines: no ipv6 router eigrp {{ item.as }}
      with_items: "{{ ipv6routing }}"
      register: print_output
    - debug: var=print_output
    - name: disable eigrp ipv6 on interfaces
      ios_config:
        parents: interface {{ item[1].id }}
        lines:
          - no ipv6 eigrp {{ item[0].as }}
      with_nested:
          - "{{ ipv6routing }}"
          - "{{ eigrp6 }}"
      register: print_output
    -  debug: var=print_output
    - name: disable ipv6 unicast-routing
      ios_config:
        lines: no ipv6 unicast-routing
      register: print_output
    - debug: var=print_output
