---
# gateway.yml
- hosts: core
  gather_facts: False
  roles:
    - role: common
    - role: interface
    - role: ipv4
    - role: ipv6
    - role: ipv4-routing
    - role: ipv6-routing
    - role: nat
    - role: recursive-dns-server
    - role: dhcp-server
    - role: write
