---
- name: REMOVE IPv4 ADDRESSES
  hosts: core
  gather_facts: false
  tasks:
    - name: configure ipv4 adresses
      ios_config:
        parents: interface {{ item.id }}
        lines:
          - no ip address 
      with_items: "{{ interface }}"
      register: print_output
    - debug: var=print_output
