---
- name: RESTORE CONFIGURATION
  hosts: cisco
  gather_facts: no
  vars:
    src_folder: "./configs"
    src: "{{ src_folder }}/{{ inventory_hostname }}.cfg"
    dest: "{{ inventory_hostname }}.cfg"
    options: "-o StrictHostKeyChecking=no"
  tasks:
    - name: CHECK THAT CONFIG FILE EXISTS
      stat:
        path: "{{ src }}"
      register: stat_result
    - name: COPY RUNNING CONFIG TO ROUTER
      command: "echo {{ ansible_ssh_pass }} | scp {{ options }} {{ src }} {{inventory_hostname}}:/{{ dest }}"
      when: stat_result.stat.exists
    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.cfg force
      when: stat_result.stat.exists
