---
- name: RESTORE CONFIGURATION
  hosts: cisco
  gather_facts: no
  vars:
    src: "./configs/{{ inventory_hostname }}.cfg"
    dest: "{{ inventory_hostname }}.cfg"
    options: "-o StrictHostKeyChecking=no"
  tasks:
    - name: COPY RUNNING CONFIG TO ROUTER
      command: "scp {{ options }} {{ src }} {{inventory_hostname}}:/{{ dest }}"
    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.cfg force
