---
# router_on_a_stick.yml
- hosts: switches
  gather_facts: False
  roles:
    - role: common
    - role: vlans
    - role: etherchannel
    - role: interface
    - role: spanning-tree
    - role: ipv4
    - role: ipv6
    - role: no-ipv4-routing
    - role: write
- hosts: routers
  gather_facts: False
  roles:
    - role: common
    - role: interface
    - role: vlans
    - role: ipv4
    - role: ipv6
    - role: ipv4-routing
    - role: ipv6-routing
    - role: nat
    - role: recursive-dns-server
    - role: dhcp-server
    - role: write
