---
- name: show interfaces configuration
  hosts: core
  gather_facts: no
  tasks:
    - name: show interfaces
      ios_command:
        commands: show ip interface brief

        wait_for:
          - result[0] contains GigabitEthernet0/7 

      register: print_output

    -  debug: var=print_output

