---
# site_to_site.yml
- hosts: core
  gather_facts: False
  roles:
    - role: common
    - role: interface
    - role: ipv4
    - role: ipv6
    - role: ipv4-routing
    - role: ipv6-routing
    - role: static-routing
    - role: rip
      when: '"rip" in ipv4.routing'
    - role: recursive-dns-server
    - role: dhcp-server
    - role: nat
    - role: write
