---
- hosts: R1
  gather_facts: False
  tasks:
    - debug:
        msg: |
            "router ospf {{ item.0.pid }}
            network {{ item.1.ipv4 }}
            "
      loop: "{{ routing | subelements('ospfv2', skip_missing=True) }}"
