---
- hosts: R1
  gather_facts: False
  tasks:
    - debug:
        msg: |
            "router ospf {{ routing.pid }}
            network {{ item.ipv4 }}
            "
      loop: "{{ routing.ospfv2 }}"
