---
- hosts: DS1
  gather_facts: False
  tasks:
    - debug:
        msg: "spanning-tree vlan {{ stp.primary | join(',') }} priority 24576"
    - name: define the stp root primary
      ios_config:
        lines: "spanning-tree vlan 1,10,30,99 priority 24576"
#        lines: "no spanning-tree vlan {{ item }} root primary"
#      loop: "{{ stp.primary }}"
#      when: stp.primary is defined
