---
# Based on https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html#playbooks-filters-ipaddr
- name: Using ipaddr filter and check on ip address variables
  hosts: R1
  gather_facts: False
  tasks:
    - name: is ipv6 link-local ?
      debug:
        msg: "Entry: {{ item.1 | ipaddr('address') | upper }} is a Link Local Address"
      loop: "{{ interfaces|subelements('ipv6_addresses', skip_missing=True) }}"
      when:
        - item.1 | ipaddr('FE80::/16')
      failed_when: >
        not item.1 | ipv6 or
        not item.1 | ipaddr('FE80::/16')
    - name: is ipv6 ula address ?
      debug:
        msg: "Entry: {{ item.1 | ipaddr('host/prefix') | upper }} is a Unique Local Address or a Global Unicast Address"
      loop: "{{ interfaces|subelements('ipv6_addresses', skip_missing=True) }}"
      when: >
        item.1 | ipaddr('FD00::/8') or
        item.1 | ipaddr('2000::/3')
      failed_when: >
        not item.1 | ipv6 or
        not item.1 | ipaddr('host/prefix') or
        not item.1 | ipaddr('FD00::/8') or
        not item.1 | ipaddr('2000::/3')
