---
# tripod.yml
- hosts: core
  gather_facts: False
  roles:
    - role: common
    - role: interface
    - role: ipv4
    - role: ipv6
    - role: ipv4-routing
    - role: ipv6-routing
    - role: fhrp
    - role: rip
      when: '"rip" in ipv4.routing'
    - role: eigrp4
      when: '"eigrp" in ipv4.routing'
    - role: ospfv2
      when: '"ospf" in ipv4.routing'
    - role: eigrp6
      when:
        - '"eigrp" in ipv6.routing'
    - role: ospfv3
      when:
        - '"ospf" in ipv6.routing'
    - role: recursive-dns-server
    - role: dhcp-server
- hosts: R1
  gather_facts: False
  roles:
    - role: nat
- hosts: core
  gather_facts: False
  roles:
    - role: write
