---
galaxy_info:
  author: goffinet
  description: enable IPv4 on interfaces
  license: CC-BY-4.0
  min_ansible_version: 2.9
  galaxy_tags:
    - cisco
    - iosv
    - ccna
    - ipv4
dependencies:
  - role: interface
