---
- name: enable eigrp4
  ios_config:
    parents: router eigrp {{ item[0].as }}
    lines:
      - router-id {{ item[0].rid }}
      - network {{ item[1].ipv4 }} 0.0.0.0
  with_nested:
      - "{{ ipv4routing }}"
      - "{{ eigrp4 }}"
- name: enable eigrp4
  ios_config:
    parents: router eigrp {{ item[0].as }}
    lines:
      - passive-interface {{ item[1] }}
  with_nested:
      - "{{ ipv4routing }}"
      - "{{ ipv4routing.passive }}"
