---
- name: enable eigrp4 rid
  ios_config:
    defaults: yes
    parents: router eigrp {{ routing.as }}
    lines:
      - eigrp router-id {{ routing.rid }}
  when:
    - routing.as is defined
    - routing.rid is defined
- name: enable eigrp4 passive-interface
  ios_config:
    defaults: yes
    parents: router eigrp {{ routing.as }}
    lines:
      - passive-interface {{ item }}
  loop: "{{ routing.passive }}"
  when:
    - routing.as is defined
    - routing.passive is defined
- name: enable eigrp4 interfaces
  ios_config:
    defaults: yes
    parents: router eigrp {{ routing.as }}
    lines:
      - "network {{ item.ipv4 }}"
  loop: "{{ routing.eigrp4 }}"
  when:
    - routing.as is defined
    - routing.eigrp4 is defined
