---
- name: enable eigrp4 rid
  ios_config:
    parents: router eigrp {{ routing.as }}
    lines:
      - router-id {{ routing.rid }}
- name: enable eigrp4 passive-interface
  ios_config:
    parents: router eigrp {{ routing.as }}
    lines:
      - passive-interface {{ item }}
  loop: "{{ routing.passive }}"
  when: routing.passive is defined
- name: enable eigrp4 interfaces
  ios_config:
    parents: router eigrp {{ routing.as }}
    lines:
      - "network {{ item.ipv4 }}"
  loop: "{{ routing.eigrp4 }}"
