---
- name: redistribute static nat route to eigrp4
  ios_config:
    defaults: yes
    parents: router eigrp {{ routing.as }}
    lines:
      - redistribute static
  when:
    - nat is defined
    - routing.as is defined
    - routing.eigrp4 is defined
